description: >
  CircleCI's Ubuntu-based machine executor VM:
  https://circleci.com/docs/2.0/executor-types/#using-machine

parameters:
  sample:
    type: string
    default: ubuntu-1604:201903-01

machine:
  image: ubuntu-1604:201903-01
  docker_layer_caching: true # default - false
